### ISSUE TITLE
Docstrings are not escaped in the /help command

### ISSUE THREAD

**Issue by thesharp** [pietroalbini/botogram#67]
Botogram sends out its help message using HTML. If you have something like `<argument>` in your docstring, Telegram will throw you an exception. Botogram should escape those symbols.

**Comment by pietroalbini** [comment]
What I'm worried about is that escaping `<`, `>` and `&` blocks any kind of rich formatting in the docstrings, which might me counter-intuitive. Although I'm having some troubles with the regexes for escaping only the non-markup entities.

**Comment by pietroalbini** [comment]
The fix is a compromise between the two solutions i mentioned above: automatically escaping everything was a no-go, because using rich formatting in docstring would be impossible with that, and escaping just the non-rich-formatting things wasn't possible without an overly complicated set of regexes.

Now docstrings are automatically escaped by botogram if the syntax detector doesn't detect any HTML formatting in it. Instead, if you explicitly use formatting you're expected to escape the entities by yourself.
